rest:
  helloservice: http://helloservice:8081
  worldservice: http://worldservice:8082
  helloworldservice: http://aggregateservice:8083
  auth-service: http://auth-service:8084

spring:
  application:
    name: api-service

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces
