rest:
  helloservice: http://helloservice:8081
  worldservice: http://worldservice:8082
  helloworldservice: http://aggregateservice:8083

spring:
  application:
    name: api-service

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-collector.istio-system
      port: 14268
